import Lean4Examples.GrahamRearrangement.Preliminaries
import Lean4Examples.GrahamRearrangement.Probability

open scoped BigOperators Pointwise

namespace GrahamRearrangement

/-!
# Section 3: definitions

Finite sample spaces and deterministic/Fourier quantities used in the proof of
Theorem 1.3.
-/

noncomputable section

/-- Uniform probability mass that a size-`m` subset of `S` has sum `z`. -/
def sliceMass {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m : ℕ) (z : ZMod p) : ℝ :=
  uniformMass (S.powersetCard m) (fun R => subsetSum R = z)

theorem sliceMass_nonneg {p m : ℕ} [NeZero p]
    (S : Finset (ZMod p)) (z : ZMod p) :
    0 ≤ sliceMass S m z :=
  uniformMass_nonneg _ _

theorem sliceMass_le_one {p m : ℕ} [NeZero p]
    (S : Finset (ZMod p)) (z : ZMod p) :
    sliceMass S m z ≤ 1 :=
  uniformMass_le_one _ _

/-- The balanced size of block `i` when `n` points are split into `m` blocks.
The first `n % m` blocks have size `n / m + 1`; the rest have size `n / m`. -/
def balancedBlockSize (n m : ℕ) (i : Fin m) : ℕ :=
  n / m + if i.val < n % m then 1 else 0

/-- Ordered balanced partitions of `S` into `m` labelled blocks. -/
def IsBalancedPartition {p m : ℕ} (S : Finset (ZMod p))
    (P : Fin m → Finset (ZMod p)) : Prop :=
  (∀ i, P i ⊆ S) ∧
  (∀ i j, i ≠ j → Disjoint (P i) (P j)) ∧
  (∀ x, x ∈ S ↔ ∃ i, x ∈ P i) ∧
  (∀ i, (P i).card = balancedBlockSize S.card m i)

/-- The finite sample space of ordered balanced partitions. -/
def balancedPartitions {p m : ℕ} [NeZero p]
    (S : Finset (ZMod p)) : Finset (Fin m → Finset (ZMod p)) := by
  classical
  exact Finset.univ.filter (IsBalancedPartition S)

/-- The block index containing `x` in a balanced partition; arbitrary outside
well-formed inputs. -/
def blockIndex {p m : ℕ} [NeZero p] (S : Finset (ZMod p))
    (P : Fin m → Finset (ZMod p)) (x : ZMod p) : Fin m := by
  classical
  by_cases hm : 0 < m
  · by_cases hP : IsBalancedPartition S P ∧ x ∈ S
    · have hex : ∃ i : Fin m, x ∈ P i := (hP.1.2.2 x).1 hP.2
      exact Classical.choose hex
    · exact ⟨0, hm⟩
  · exact Fin.elim0 (by simpa [Nat.not_lt] using hm)

theorem mem_blockIndex {p m : ℕ} [NeZero p] (S : Finset (ZMod p))
    (P : Fin m → Finset (ZMod p)) (x : ZMod p)
    (hm : 0 < m) (hP : IsBalancedPartition S P) (hx : x ∈ S) :
    x ∈ P (blockIndex S P x) := by
  classical
  unfold blockIndex
  simp [hm, hP, hx, Classical.choose_spec]

/-- The block containing a given point. -/
def pointBlock {p m : ℕ} [NeZero p] (S : Finset (ZMod p))
    (P : Fin m → Finset (ZMod p)) (x : ZMod p) : Finset (ZMod p) :=
  P (blockIndex S P x)

/-- Conditional choices of one point from each block. -/
def blockChoices {p m : ℕ} [NeZero p]
    (P : Fin m → Finset (ZMod p)) : Finset (Fin m → ZMod p) :=
  Finset.univ.pi P

/-- The chosen subset generated by one point from each block. -/
def choiceSet {p m : ℕ} (X : Fin m → ZMod p) : Finset (ZMod p) :=
  Finset.univ.image X

/-- Sum of one point chosen from each block. -/
def choiceSum {p m : ℕ} (X : Fin m → ZMod p) : ZMod p :=
  ∑ i, X i

/-- Conditional point mass of the block-choice sum. -/
def conditionalSumMass {p m : ℕ} [NeZero p]
    (P : Fin m → Finset (ZMod p)) (z : ZMod p) : ℝ :=
  uniformMass (blockChoices P) (fun X => choiceSum X = z)

/-- Average over the balanced-partition sample space. -/
def partitionExpectation {p m : ℕ} [NeZero p]
    (S : Finset (ZMod p))
    (F : (Fin m → Finset (ZMod p)) → ℝ) : ℝ :=
  uniformExpectation (balancedPartitions S) F

/-- Probability of an event over the uniformly random balanced partition. -/
def partitionMass {p m : ℕ} [NeZero p]
    (S : Finset (ZMod p))
    (E : (Fin m → Finset (ZMod p)) → Prop)
    [DecidablePred E] : ℝ :=
  uniformMass (balancedPartitions S) E

/-- The paper's random-partition quantity `ψ(χ)`. -/
def psi {p m : ℕ} [NeZero p]
    (P : Fin m → Finset (ZMod p)) (χ : ZMod p) : ℝ :=
  ∑ i,
    (1 / ((P i).card : ℝ) ^ 2) *
      ∑ x ∈ P i, ∑ x' ∈ P i,
        zmodNorm (χ * x - χ * x') ^ 2

/-- The deterministic comparison quantity `Ψ(χ)`. -/
def Psi {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m : ℕ) (χ : ZMod p) : ℝ :=
  (m : ℝ) / (S.card : ℝ) ^ 2 *
    ∑ x ∈ S, ∑ x' ∈ S,
      zmodNorm (χ * x - χ * x') ^ 2

/-- The dyadic low-`ψ` set `A₀`. -/
def A0 {p m : ℕ} [NeZero p]
    (P : Fin m → Finset (ZMod p)) : Finset (ZMod p) :=
  Finset.univ.filter fun χ => psi P χ < 1

/-- The dyadic shell `A_t={χ:t≤ψ(χ)<2t}`. -/
def At {p m : ℕ} [NeZero p]
    (P : Fin m → Finset (ZMod p)) (t : ℕ) : Finset (ZMod p) :=
  Finset.univ.filter fun χ => (t : ℝ) ≤ psi P χ ∧ psi P χ < 2 * t

/-- The deterministic low-energy set `B_t`. -/
def Bset {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m t : ℕ) : Finset (ZMod p) :=
  Finset.univ.filter fun χ => Psi S m χ ≤ t

/-- Points of `S` within the `8 sqrt(t/m)` ball about `y` after dilation by `χ`. -/
def nearSet {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m t : ℕ) (χ y : ZMod p) : Finset (ZMod p) :=
  S.filter fun x =>
    zmodNorm (χ * x - y) ≤ 8 * Real.sqrt ((t : ℝ) / m)

/-- The deterministic structured-character set `D_t`. -/
def Dset {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m t : ℕ) : Finset (ZMod p) :=
  Finset.univ.filter fun χ =>
    χ ≠ 0 ∧ ∃ y : ZMod p, 3 * S.card ≤ 4 * (nearSet S m t χ y).card

/-- There is some positive scale at which `χ` belongs to `D_t`. -/
def HasDTime {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m : ℕ) (χ : ZMod p) : Prop :=
  ∃ t : ℕ, 0 < t ∧ χ ∈ Dset S m t

/-- The smallest positive scale at which `χ ∈ D_t`, whenever such a scale
exists. This is the scale used in the paper to choose a center independent of
the later value of `t`. -/
def firstDTime {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m : ℕ) (χ : ZMod p) : ℕ := by
  classical
  by_cases h : HasDTime S m χ
  · exact Nat.find h
  · exact 1

theorem firstDTime_spec {p : ℕ} [NeZero p]
    (S : Finset (ZMod p)) (m : ℕ) (χ : ZMod p)
    (h : HasDTime S m χ) :
    0 < firstDTime S m χ ∧
      χ ∈ Dset S m (firstDTime S m χ) := by
  classical
  simp [firstDTime, h, Nat.find_spec h]

theorem firstDTime_le {p : ℕ} [NeZero p]
    (S : Finset (ZMod p)) (m t : ℕ) (χ : ZMod p)
    (ht : 0 < t) (hχ : χ ∈ Dset S m t) :
    firstDTime S m χ ≤ t := by
  classical
  have hex : HasDTime S m χ := ⟨t, ht, hχ⟩
  simp [firstDTime, hex]
  exact Nat.find_min' hex ⟨ht, hχ⟩

theorem nearSet_mono_t {p : ℕ} [NeZero p]
    (S : Finset (ZMod p)) (m t₁ t₂ : ℕ)
    (χ y : ZMod p) (htt : t₁ ≤ t₂) :
    nearSet S m t₁ χ y ⊆ nearSet S m t₂ χ y := by
  intro x hx
  simp only [nearSet, Finset.mem_filter] at hx ⊢
  refine ⟨hx.1, le_trans hx.2 ?_⟩
  gcongr

/-- The paper's center `yχ`, chosen once and for all from the smallest positive
scale at which `χ ∈ D_t`. The formal parameter `t` is intentionally ignored,
so the center is definitionally independent of `t`. -/
def centerAt {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m : ℕ) (_t : ℕ) (χ : ZMod p) : ZMod p := by
  classical
  by_cases h : HasDTime S m χ
  · have hD :
        χ ∈ Dset S m (firstDTime S m χ) :=
      (firstDTime_spec S m χ h).2
    exact Classical.choose
      ((Finset.mem_filter.1 hD).2.2)
  · exact 0

theorem centerAt_independent_of_t {p : ℕ} [NeZero p]
    (S : Finset (ZMod p)) (m t₁ t₂ : ℕ) (χ : ZMod p) :
    centerAt S m t₁ χ = centerAt S m t₂ χ := by
  rfl

theorem centerAt_spec {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m t : ℕ) {χ : ZMod p} (ht : 0 < t)
    (hχ : χ ∈ Dset S m t) :
    3 * S.card ≤
      4 * (nearSet S m t χ (centerAt S m t χ)).card := by
  classical
  have hex : HasDTime S m χ := ⟨t, ht, hχ⟩
  have hD :
      χ ∈ Dset S m (firstDTime S m χ) :=
    (firstDTime_spec S m χ hex).2
  have hcenter :
      3 * S.card ≤
        4 * (nearSet S m (firstDTime S m χ) χ
          (centerAt S m t χ)).card := by
    simpa [centerAt, hex] using
      Classical.choose_spec ((Finset.mem_filter.1 hD).2.2)
  have hsubset :
      nearSet S m (firstDTime S m χ) χ (centerAt S m t χ) ⊆
        nearSet S m t χ (centerAt S m t χ) :=
    nearSet_mono_t S m (firstDTime S m χ) t χ
      (centerAt S m t χ) (firstDTime_le S m t χ ht hχ)
  exact le_trans hcenter (Nat.mul_le_mul_left 4 (Finset.card_le_card hsubset))

/-- The enlarged set `J_{χ,t} ⊆ Z_p` used in Lemmas 3.2 and 3.3. -/
def Jset {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m t : ℕ) (χ : ZMod p) : Finset (ZMod p) :=
  Finset.univ.filter fun x =>
    zmodNorm (χ * x - centerAt S m t χ) ≤
      16 * Real.sqrt ((t : ℝ) / m)

/-- The set `Q_{t,δ}` from Lemma 3.4. -/
def Qset {p : ℕ} [NeZero p] (S : Finset (ZMod p))
    (m t : ℕ) (δ : ℝ) : Finset (ZMod p) :=
  Finset.univ.filter fun x =>
    (∑ χ ∈ Bset S m t, zmodNorm (χ * x) ^ 2) <
      δ * (Bset S m t).card

/-- Theorem 1.3 exactly in finite-cardinality probability language. -/
def Theorem13Statement : Prop :=
  ∃ C : ℝ, 0 < C ∧
    ∀ (p : ℕ) (hp : p.Prime),
      letI : NeZero p := ⟨hp.ne_zero⟩
      ∀ (S : Finset (ZMod p)), 2 ≤ S.card →
      ∀ (m : ℕ),
        C * Real.log (S.card : ℝ) ≤ (m : ℝ) →
        (m : ℝ) ≤ (1 / 1000 : ℝ) * S.card / Real.log (S.card : ℝ) →
        ∀ z : ZMod p,
          sliceMass S m z ≤
            1 / (p : ℝ) + C / ((S.card : ℝ) * Real.sqrt (m : ℝ))

end

end GrahamRearrangement
