name: Lean

on:
  push:
    branches:
      - formalize-graham-rearrangement
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build: false
          test: false
          lint: false
      - name: Check Graham rearrangement formalization
        run: lake env lean Lean4Examples/graham-rearrangement.lean
